import NavTop from "./layouts/navTop"
import '../public/styles/index.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <title>Ddbase</title>
      </head>
      <body style={{ margin: 0}}>
        <div className="gradient-container">
          <NavTop />
          {children}
        </div>
      </body>
    </html>
  )
}
